ekyna_cart_index:
    pattern: /cart
    defaults:
        _controller: EkynaCartBundle:Cart:index
    requirements:
        _method: GET|POST
    options:
        _cms:
            name: Mon panier
            menus: [footer]
            position: 98
            seo:
                follow: false
                index: false

ekyna_cart_informations:
    pattern: /cart/informations
    defaults:
        _controller: EkynaCartBundle:Cart:informations
    requirements:
        _method: GET|POST
    options:
        _cms:
            parent: ekyna_cart_index
            name: Mes informations

ekyna_cart_shipment:
    pattern: /cart/shipment
    defaults:
        _controller: EkynaCartBundle:Cart:shipment
    requirements:
        _method: GET|POST
    options:
        _cms:
            parent: ekyna_cart_index
            name: Mode de livraisons

ekyna_cart_payment:
    pattern: /cart/payment
    defaults:
        _controller: EkynaCartBundle:Cart:payment
    requirements:
        _method: GET|POST
    options:
        _cms:
            parent: ekyna_cart_index
            name: Moyen de paiement

ekyna_cart_confirmation:
    pattern: /cart/confirmation/{key}
    defaults:
        _controller: EkynaCartBundle:Cart:confirmation
    requirements:
        _method: GET
        key: "[\w-_]{32}"
    options:
        _cms:
            parent: ekyna_cart_index
            name: Confirmation

ekyna_cart_reset:
    pattern: /cart/reset
    defaults:
        _controller: EkynaCartBundle:Cart:reset
    requirements:
        _method: GET

ekyna_cart_remove_item:
    pattern: /cart/remove-item/{itemId}
    defaults:
        _controller: EkynaCartBundle:Cart:removeItem
    requirements:
        _method: GET|POST
        itemId: \d+
