ekyna_cart_index:
    path: /cart
    defaults:
        _controller: EkynaCartBundle:Cart:index
    methods: [GET|POST]
    options:
        _cms:
            name: Mon panier
            menus: [footer]
            position: 98
            seo:
                follow: false
                index: false

ekyna_cart_informations:
    path: /cart/informations
    defaults:
        _controller: EkynaCartBundle:Cart:informations
    methods: [GET|POST]
    options:
        _cms:
            parent: ekyna_cart_index
            name: Mes informations

ekyna_cart_shipment:
    path: /cart/shipment
    defaults:
        _controller: EkynaCartBundle:Cart:shipment
    methods: [GET|POST]
    options:
        _cms:
            parent: ekyna_cart_index
            name: Mode de livraisons

ekyna_cart_payment:
    path: /cart/payment
    defaults:
        _controller: EkynaCartBundle:Cart:payment
    methods: [GET|POST]
    options:
        _cms:
            parent: ekyna_cart_index
            name: Moyen de paiement

ekyna_cart_confirmation:
    path: /cart/confirmation/{orderKey}-{paymentId}
    defaults:
        _controller: EkynaCartBundle:Cart:confirmation
    methods: [GET]
    requirements:
        orderKey: "[a-zA-Z\d]{32}"
        paymentId: \d+
    options:
        _cms:
            parent: ekyna_cart_index
            name: Confirmation

ekyna_cart_reset:
    path: /cart/reset
    defaults:
        _controller: EkynaCartBundle:Cart:reset
    methods: [GET]

ekyna_cart_remove_item:
    path: /cart/remove-item/{itemId}
    defaults:
        _controller: EkynaCartBundle:Cart:removeItem
    methods: [GET|POST]
    requirements:
        itemId: \d+
